### PR TITLE
Map fix

### PR DESCRIPTION
**Pull request by contygm**

### CODE REVIEW

**Comment by marymiller1954** [comment]
I still got the error.  Also, now when I click on Next Page, then Click on
Back, the screen looks different than before.   The dates are still filled
in on the tour stops, but no locations appear and it doesn't let me add any.

**Comment by marymiller1954** [comment]
But I do see that the html for the last tour stop on Index2 page has been
fixed :-)

**Comment by contygm** [comment]
this is what I'm seeing

what are you seeing

**Comment by contygm** [comment]
mine clears out the fields if you go from the event page and back, but you
can still add cities

**Comment by marymiller1954** [comment]
Hey sorry, I've been in debugging hell for the last hour, getting no
where!  It seems like my javascript doesn't recognize the Next Page button
being click, because according to the console log it enters the script but
stops before the OnClick function.   I'm going to stop for today and
hopefully fresh eyes in the morning will help.

Thanks for helping today.

**Comment by contygm** [comment]
mk, if you need me tomorrow, just shoot me an email

**Comment by marymiller1954** [comment]
I will.   Thanks!   I'm still getting the inner,html error.   I wonder if
there is a difference between running in Windows versus Mac.

**Comment by contygm** [comment]
I'll look at it again.

just to be safe, did you clone the current master and start working from
there? I noticed your the branch named "mary" looked old

**Comment by marymiller1954** [comment]
I did clone the master.

**Comment by contygm** [comment]
also, send me screen shots when you can (tomorrow is cool)

i think that might help

**Comment by marymiller1954** [comment]
I will first thing tomorrow.

**Pull request merged**
